feature: interceptando response e apagando token caso seja 401
henriqueyun/arara-store-frontend pull request #14
Opened 2023-05-21 01:46 UTC by coutocouto

2023-05-22 04:59 UTC, henriqueyun requested changes

2023-05-22 04:59 UTC, henriqueyun commented on src/client/client.js
> +axios.interceptors.response.use(
Meter isso dentro de uma funçãozinha

2023-05-22 04:59 UTC, henriqueyun commented on src/client/client.js
> +      originalRequest.url === 'http://localhost:3000/login/'
Será que tem que passar a URL completa aqui? Só /login não resolveria? De toda forma poderia ser para `axios.defaults.baseURL`

2023-05-22 16:13 UTC, coutocouto commented on src/client/client.js
> +axios.interceptors.response.use(
por que? em que lugar eu chamaria essa função? ou seria uma func auto chamaada, por que essa config tem que se feita no inicio da aplicação

2023-05-22 16:14 UTC, coutocouto commented on src/client/client.js
> +      originalRequest.url === 'http://localhost:3000/login/'
eu sei la, peguei isso da doc pronto

2023-05-22 19:10 UTC, coutocouto commented on src/client/client.js
> +      originalRequest.url === 'http://localhost:3000/login/'
retirei essa parte, isso só faz sentido quando e pra logar, mas tamo usando pra toda pagina

2023-05-23 08:02 UTC, henriqueyun approved these changes
Só resolver os conflitos @coutocouto

2023-05-23 18:19 UTC, merged