[FRONTEND] Criar Telas de Fluxo de Pedido
henriqueyun/arara-store-frontend pull request #20
Opened 2023-05-26 16:36 UTC by henriqueyun

2023-05-26 16:47 UTC, henriqueyun commented on src/app/components/AddressForm.jsx
> +import { Box, Button, Grid, Stack, TextField, Tooltip } from '@mui/material';
Dividir partes do componente em partes menores; adicionar também o campo de descrição quando a [tarefa do backend for concluída](tinyurl.com/48awc3zj); melhorar nomes dos campos e variáveis utilizadas.

2023-05-26 16:47 UTC, henriqueyun commented on package.json
> +    "react-redux": "^8.0.5",
Remover, não está utilizando react-redux

2023-05-26 16:47 UTC, henriqueyun commented on src/app/theme/Theme.js
> +    MuiMenuItem: {
Horrível isso

2023-05-26 16:47 UTC, henriqueyun commented on src/app/pages/Order.jsx
> +    // TODO: refactor
Remover comentário

2023-05-26 16:47 UTC, henriqueyun commented on src/app/pages/Order.jsx
> +    statusOrder: 'waiting payment',
Remover quando as [mudanças no pedido ficarem prontas](https://trello.com/c/T2StmnaZ/71-backend-mudan%C3%A7as-pedido)

2023-05-26 16:47 UTC, henriqueyun commented on src/app/pages/Order.jsx
> +import {
Refatorar e dividir código em pequenas partes

2023-05-31 22:23 UTC, henriqueyun commented on src/app/theme/Theme.js
> +    MuiMenuItem: {
Mas nada a fazer

2023-05-31 22:24 UTC, henriqueyun commented on src/app/components/AddressForm.jsx
> +import { Box, Button, Grid, Stack, TextField, Tooltip } from '@mui/material';
@coutocouto dá uma testada nisso por favor.

2023-05-31 22:29 UTC, henriqueyun reviewed
LGTM

2023-06-01 03:23 UTC, coutocouto requested changes
se arrumar oq eu falei pode mergea, se tiver duvida chama call

2023-06-01 03:23 UTC, coutocouto commented on src/app/components/AddressForm.jsx
> +  const clearState = {
Ta dando erro, vc pediu o novo campo de nome la e não colocou aqui pra criar
o nome do campo e description, onde e colocar o nome do endereço, e usa ele pra selecionar os endereço no select tb

2023-06-01 03:23 UTC, coutocouto commented on src/app/pages/Order.jsx
> +function OrderItem({ item }) {
Coloca ou na foto ou no nome, ou nos dois para quando clicar redirecionar para a pagina do produto, para mi me muito util, para antes de comprar, confirmar se o que eu to comprando esta correto

2023-06-01 03:23 UTC, coutocouto commented on src/app/storage/index.js
se vc não imagina outros usos de storage, não precisa da index, e sim do export default, e bom deixar como export default e só criar a index caso apareça outro caso de storage, o mesmo para pasta theme, index de export para um item não e bom

2023-06-01 03:23 UTC, coutocouto commented on src/app/storage/addressStorage.js
apaga esse arquivo se não for usar

2023-06-01 03:23 UTC, coutocouto commented on src/client/services/order.js
padrozinar os nomes de req, em algums lugares ta "add" e aqui esta "send"

2023-06-01 03:23 UTC, coutocouto commented on yarn.lock
isso não devia estar no gitignore?

2023-06-01 03:35 UTC, coutocouto commented
Aproveita e muda todos os alert para o Swal
ex: 
Erro: 
Swal.fire({
        icon: 'error',
        title: 'Erro',
        text: 'Preencha todos os campos!'
      })

Sucesso: 
Swal.fire({
        icon: 'success',
        title: 'Sucesso',
        text: 'Produto Cadastrado',
        didClose: () => { // serve para fazer algo quando fechar o popup
          window.location.reload()
        }

2023-06-02 13:49 UTC, henriqueyun commented on src/app/storage/index.js
mim gostar

2023-06-02 13:51 UTC, henriqueyun commented on src/client/services/order.js
São métodos diferentes

2023-06-02 13:52 UTC, henriqueyun commented on yarn.lock
Nope

2023-06-02 13:53 UTC, henriqueyun commented on src/app/components/AddressForm.jsx
> +  const clearState = {
> Aproveita e muda todos os alert para o Swal ex: Erro: Swal.fire({ icon: 'error', title: 'Erro', text: 'Preencha todos os campos!' })
> 
> Sucesso: Swal.fire({ icon: 'success', title: 'Sucesso', text: 'Produto Cadastrado', didClose: () => { // serve para fazer algo quando fechar o popup window.location.reload() }

Como isso vai ter que mexer em mais lugares, deixa pra uma outra task

2023-06-02 13:55 UTC, henriqueyun commented
> Aproveita e muda todos os alert para o Swal ex: Erro: Swal.fire({ icon: 'error', title: 'Erro', text: 'Preencha todos os campos!' })
> 
> Sucesso: Swal.fire({ icon: 'success', title: 'Sucesso', text: 'Produto Cadastrado', didClose: () => { // serve para fazer algo quando fechar o popup window.location.reload() }

Como precisa mexer em mais lugares, deixa pra uma task só disso

2023-06-02 21:21 UTC, coutocouto approved these changes

2023-06-02 21:22 UTC, merged