Draft: [FRONTEND] Tela de detalhes do pedido
henriqueyun/arara-store-frontend pull request #24
Opened 2023-06-07 00:11 UTC by coutocouto

2023-06-07 20:19 UTC, henriqueyun requested changes

2023-06-07 20:19 UTC, henriqueyun commented on src/app/components/AddressContent.jsx
> +              )}
Usar &&, para que não seja necessário retornar `<></>`

2023-06-07 20:19 UTC, henriqueyun commented on src/app/components/AddressForm.jsx
> +    if (fullAddress?.id) {
Estamos com pressa, então pode deixar assim. Mas essa function furou firme a responsa única, seria legal ter feito uma updateAddress e feito a validação em quem dispara a function

2023-06-07 20:19 UTC, henriqueyun commented on src/app/components/OrderContent.jsx
> +    'Pagamento Efetuado': '#00CC00',
Seria legal termos cores do Theme.js

2023-06-07 20:19 UTC, henriqueyun commented on src/app/components/OrderContent.jsx
> +                <></>
Trocar `?` para `&&` para não retornar o `<></>`

2023-06-07 20:19 UTC, henriqueyun commented on src/app/pages/Order.jsx
> +            orderPrice={formatCurrency(calculateOrderPrice(cart))}
O ideal seria enviar só `cart.items` já que as props. de `cart` não são utilizadas

2023-06-07 20:19 UTC, henriqueyun commented on src/app/pages/OrderDetails.jsx
> +import {
Tá faltando as correções que fizemos com o Prada aqui

2023-06-07 20:19 UTC, henriqueyun commented on src/app/pages/Profile.jsx
> +/* eslint-disable no-unused-vars */
Remover comentário

2023-06-07 20:19 UTC, henriqueyun commented on src/app/util/index.js
> +};
https://github.com/henriqueyun/arara-store-frontend/pull/23#discussion_r1222095385

2023-06-08 02:52 UTC, coutocouto commented on src/app/components/OrderContent.jsx
> +    'Pagamento Efetuado': '#00CC00',
não sei usar isso

2023-06-08 02:53 UTC, coutocouto commented on src/app/pages/OrderDetails.jsx
> +import {
ta na outra pr em draft

2023-06-08 03:17 UTC, henriqueyun commented
Corrigido na #25

2023-06-08 03:17 UTC, closed without merging