FRONTEND] Criar Tela de Carrinho
henriqueyun/arara-store-frontend pull request #5
Opened 2023-05-06 05:35 UTC by henriqueyun

[[FRONTEND] Criar Tela de Carrinho](https://trello.com/c/fnz1QX5X/40-frontend-criar-tela-de-carrinho)

2023-05-20 00:09 UTC, henriqueyun commented on src/client/services/cart.js
> +        cartId: 1,
`cartId`chumbado, deve ser pego do sessionStorage

2023-05-20 19:31 UTC, henriqueyun commented on src/client/services/cart.js
> +    list: async () => {
Tem que ter filtro também, eu não sei como usar nem se está disponível

2023-05-20 19:34 UTC, henriqueyun commented
Só remover de draft quando for feito rebase da feature de sessionStorage e forem removidos os acessos com dados _hardcoded_  à API

2023-05-22 19:23 UTC, coutocouto requested changes

2023-05-22 19:23 UTC, coutocouto commented on src/app/pages/Cart.jsx
na quantidade precisa ter um + e - para poder escolher a quantidade de produtos

2023-05-22 19:23 UTC, coutocouto commented on src/app/pages/Cart.jsx
> +      const cart = await client.cart.find(id);
ele traz um carrinho com os items dentro apenas, n tem como diminuir

2023-05-23 03:52 UTC, henriqueyun commented on src/app/pages/Cart.jsx
> +      const cart = await client.cart.find(id);
Na descrição do Trello explico que é só fazer uma req. para trazer dados únicamente do carrinho (sem incluir mais nada) e outra para trazer o carrinho incluindo itens, produtos etc.

2023-05-23 04:03 UTC, henriqueyun commented on src/app/pages/Cart.jsx
Eu tinha deixado como [TODO](https://github.com/henriqueyun/arara-store-frontend/blob/d51450104d06461302f0cc5a3acbfee357994665/src/app/pages/Cart.jsx#LL126C15-L126C15) porque não sabia como implementar, mas agora tenho idéia e vou lançar.

2023-05-23 05:25 UTC, coutocouto approved these changes

2023-05-23 05:25 UTC, merged