feat: fazendo o botão de logout
henriqueyun/arara-store-frontend pull request #9
Opened 2023-05-13 00:38 UTC by coutocouto

2023-05-15 19:23 UTC, henriqueyun commented
Parece clean até agora

2023-05-22 05:01 UTC, henriqueyun requested changes

2023-05-22 05:01 UTC, henriqueyun commented on src/app/components/Menubar.jsx
> +      // TODO: fazer ele redirecionar para a tela de login useNavigate não funciona aqui
Remover comentário. Acho que não é necessário redirecionar para login, acho que só recarregar a página atual já seria o suficiente.

2023-05-22 19:03 UTC, coutocouto commented on src/app/components/Menubar.jsx
> +      // TODO: fazer ele redirecionar para a tela de login useNavigate não funciona aqui
pronto

2023-05-23 08:00 UTC, henriqueyun approved these changes

2023-05-23 08:00 UTC, merged